CREATE DATABASE OFICINA;
USE OFICINA;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	ID_CARRO INT UNIQUE
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('CEL','RES','COM') NOT NULL,
	NUMERO VARCHAR(30) NOT NULL,
	ID_CLIENTE INT
);

CREATE TABLE COR(
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
	COR VARCHAR(30) UNIQUE
);

CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
	MODELO VARCHAR(30) NOT NULL,
	PLACA VARCHAR(30) NOT NULL UNIQUE,
	ID_MARCA INT
);

CREATE TABLE MARCA(
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(30) UNIQUE
);

CREATE TABLE CARRO_COR(
	ID_CARRO INT,
	ID_COR INT,
	PRIMARY KEY (ID_CARRO,ID_COR)
);

ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(IDCLIENTE);

ALTER TABLE CARRO
ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(ID_MARCA)
REFERENCES MARCA(IDMARCA);

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_COR
FOREIGN KEY(ID_COR)
REFERENCES COR(IDCOR);

ALTER TABLE CARRO_COR
ADD CONSTRAINT FK_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARRO(IDCARRO);

INSERT INTO MARCA VALUES(NULL,'HYUNDAI');
INSERT INTO MARCA VALUES(NULL,'CHEVROLET');
INSERT INTO MARCA VALUES(NULL,'FORD');
INSERT INTO MARCA VALUES(NULL,'FIAT');
INSERT INTO MARCA VALUES(NULL,'KIA');
INSERT INTO MARCA VALUES(NULL,'YAMAHA');

INSERT INTO CARRO VALUES(NULL,'HB20','JJG1212',1);
INSERT INTO CARRO VALUES(NULL,'ASTRA','DMV3530',2);
INSERT INTO CARRO VALUES(NULL,'ECOSPORT','FUI1976',3);
INSERT INTO CARRO VALUES(NULL,'TEMPRA','ELA1256',4);
INSERT INTO CARRO VALUES(NULL,'SORENTO','TIC5500',5);
INSERT INTO CARRO VALUES(NULL,'NMAX','EZF8370',6);
INSERT INTO CARRO VALUES(NULL,'KADETT','OPA1302',2);
INSERT INTO CARRO VALUES(NULL,'KA','IUI2007',3);
INSERT INTO CARRO VALUES(NULL,'CORSA','ELE1901',2);
INSERT INTO CARRO VALUES(NULL,'MONZA','VIV1211',2);

INSERT INTO COR VALUES(NULL,'BRANCO');
INSERT INTO COR VALUES(NULL,'PEROLADO');
INSERT INTO COR VALUES(NULL,'AZUL');
INSERT INTO COR VALUES(NULL,'TURQUESA');
INSERT INTO COR VALUES(NULL,'VERMELHO');
INSERT INTO COR VALUES(NULL,'VINHO');
INSERT INTO COR VALUES(NULL,'MARROM');
INSERT INTO COR VALUES(NULL,'LARANJA');
INSERT INTO COR VALUES(NULL,'VERDE');
INSERT INTO COR VALUES(NULL,'ESMERALDA');
INSERT INTO COR VALUES(NULL,'AMARELA');
INSERT INTO COR VALUES(NULL,'DOURADO');

INSERT INTO CLIENTE VALUES(NULL,'AARON DRIVER','M',11);
INSERT INTO CLIENTE VALUES(NULL,'DANIKA KELLER','F',12);
INSERT INTO CLIENTE VALUES(NULL,'JORDY COBB','M',13);
INSERT INTO CLIENTE VALUES(NULL,'JAQUELINE MAHER','F',14);
INSERT INTO CLIENTE VALUES(NULL,'RANDALL NELSON','M',15);
INSERT INTO CLIENTE VALUES(NULL,'ANA FOFAO','F',16);
INSERT INTO CLIENTE VALUES(NULL,'DONALD RODGERS','M',17);
INSERT INTO CLIENTE VALUES(NULL,'FERNANDA MOSER','F',18);
INSERT INTO CLIENTE VALUES(NULL,'GERONIMO MATEUS','M',19);
INSERT INTO CLIENTE VALUES(NULL,'PAULA VENTURA','F',20);

INSERT INTO TELEFONE VALUES(NULL,'CEL','99999998',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','99993998',2);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99999958',3);
INSERT INTO TELEFONE VALUES(NULL,'COM','99929998',4);
INSERT INTO TELEFONE VALUES(NULL,'CEL','92399998',5);
INSERT INTO TELEFONE VALUES(NULL,'RES','95599998',6);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99169998',7);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99978998',9);
INSERT INTO TELEFONE VALUES(NULL,'RES','99912998',10);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99923998',1);
INSERT INTO TELEFONE VALUES(NULL,'RES','99773998',2);
INSERT INTO TELEFONE VALUES(NULL,'CEL','99993458',3);
INSERT INTO TELEFONE VALUES(NULL,'COM','99922998',4);

INSERT INTO CARRO_COR VALUES(11,4);
INSERT INTO CARRO_COR VALUES(11,6);
INSERT INTO CARRO_COR VALUES(12,9);
INSERT INTO CARRO_COR VALUES(12,12);
INSERT INTO CARRO_COR VALUES(13,5);
INSERT INTO CARRO_COR VALUES(13,8);
INSERT INTO CARRO_COR VALUES(14,1);
INSERT INTO CARRO_COR VALUES(14,3);
INSERT INTO CARRO_COR VALUES(15,11);
INSERT INTO CARRO_COR VALUES(15,10);
INSERT INTO CARRO_COR VALUES(16,9);
INSERT INTO CARRO_COR VALUES(16,6);
INSERT INTO CARRO_COR VALUES(17,3);
INSERT INTO CARRO_COR VALUES(17,7);
INSERT INTO CARRO_COR VALUES(18,1);
INSERT INTO CARRO_COR VALUES(18,12);
INSERT INTO CARRO_COR VALUES(19,11);
INSERT INTO CARRO_COR VALUES(19,4);
INSERT INTO CARRO_COR VALUES(20,5);
INSERT INTO CARRO_COR VALUES(20,8);
INSERT INTO CARRO_COR VALUES(14,2);
INSERT INTO CARRO_COR VALUES(16,7);
INSERT INTO CARRO_COR VALUES(20,2);
INSERT INTO CARRO_COR VALUES(12,10);

--AS MARCAS DOS CARROS DE CADA CLIENTE:
SELECT IDCLIENTE, NOME, MARCA
FROM CLIENTE
INNER JOIN CARRO
ON CLIENTE.ID_CARRO = CARRO.IDCARRO
INNER JOIN MARCA
ON CARRO.ID_MARCA = MARCA.IDMARCA;

--AS MARCAS DOS CARROS DAS MULHERES:
SELECT CL.NOME, M.MARCA
FROM CLIENTE CL
INNER JOIN CARRO CA
ON CL.ID_CARRO = CA.IDCARRO
INNER JOIN MARCA M
ON CA.ID_MARCA = M.IDMARCA
WHERE CL.SEXO = 'F';

-- TELEFONES DE QUEM TEM CARROS NA COR AMARELA:
SELECT CL.NOME, T.NUMERO, CA.MODELO, COR
FROM CLIENTE CL
INNER JOIN TELEFONE T
ON CL.IDCLIENTE = T.ID_CLIENTE
INNER JOIN CARRO CA
ON CL.ID_CARRO = CA.IDCARRO
INNER JOIN COR
ON CA.IDCARRO = COR.IDCOR;
WHERE CL.SEXO = 'F';
